### ISSUE TITLE
Request: choose result type, return url or the original .gif url

### ISSUE THREAD

**Issue by puyt** [halvves/zazu-giphy#1]
It would be nice if the user could choose which type of result the plugin returns. Some chats don't support preview if the URL doesn't end with `.gif`

**Comment by mmmerl** [comment]
Good idea. I was definitely torn with which version of the giphy gif should be copied on action. I could add a flag like `-r` for raw, but I want to see if we can get Zazu to support keyboard modifiers in much the same way that Alfred does (tinytacoteam/zazu#245). It would be nice to perform a regular action for giphy url and maybe alt-action for raw url... or something of that sort. What are your thoughts?

**Comment by puyt** [comment]
Having keyboard modifiers in Zazu would indeed be an nice addition but I still think I'd love to change the default return value via the variables in the `.zazurc.json`.
Because at this moment with my current chat clients I would always have to use the -r flag or the `alt + click`.

**Comment by mmmerl** [comment]
resolved by #2 

will open another issue for modifier keys if and when we can get them into zazu proper re: tinytacoteam/zazu#245
