### ISSUE TITLE
allow more configuration

### ISSUE THREAD

**Issue by mmmerl** [halvves/zazu-giphy#3]
@puyt wanted to run this by you before I implemented, since it would be a bit of a breaking change...

I'm thinking of making it to where anyone that knows the giphy api (we can document the options here in our README as well) can choose which source they want out of all the available giphy options. I'm thinking of namespacing the variable in the event that we can use modifier keys ("src_alt", "src_ctrl", etc...). This allows a bit more flexibility than "returnRaw", but I wanted to give you a heads up as this is going to change a var name.

```
"variables": {
  "src_main": "images.fixed_height.url"
}
```

See #4

**Comment by puyt** [comment]
@halvves this would be better indeed 👍

**Comment by mmmerl** [comment]
solved by #4
